services:
  artman:
    build:
      context: artman
      dockerfile: dockerfile
    volumes:
      - ./artman/:/app
    network_mode: host
    restart: always

  qlcplus:
    image: scotttag/qlcplus-docker
    ports:
      - "5800:5800"  # Web interface
      - "5900:5900"  # VNC
      - "80:9999"  # QLC+ web server
    volumes:
      - ./qlc-configs:/data:rw
      - ./qlc-fixtures:/usr/share/qlcplus/fixtures/custom:ro
    environment:
      - QLC_WEB_SERVER=true
      - WORKSPACE_FILE=/data/active.qxw
      - OPERATE_MODE=true 
    restart: always
    networks:
      network:
        ipv4_address: 172.55.0.2

volumes:
  qlcplus-data:
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.0.0/24

