services:
  artman:
    build:
      context: artman
      dockerfile: dockerfile
    volumes:
      - ./artman/:/app
    network_mode: host
    restart: always
    networks:
      network:
        ipv4_address: 172.18.0.2

  qlc-plus:
    image: averyout48/qlc-plus-docker
    depends_on:
      - artman
    volumes:
      - ./qlc-configs/active.qxw:/QLC/qlc.qxw
    ports:
      - "80:9999"
    restart: always
    networks:
      network:
        ipv4_address: 172.18.0.3
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
