services:
  artman:
    build:
      context: artman
      dockerfile: dockerfile
    volumes:
      - ./artman/:/app
    network_mode: host
    restart: unless-stopped


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.0.0/24
